name: Cypress End-to-End Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Inicializar Projeto e Instalar Cypress
        run: |
          npm init -y
          npm install cypress --save-dev

      - name: Executar Testes do Cypress
        # Adicionamos o --headless aqui para rodar em segundo plano na nuvem
        run: npx cypress run --browser chrome --headless
